// <auto-generated />
namespace EventDay.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class poprawkievents2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(poprawkievents2));
        
        string IMigrationMetadata.Id
        {
            get { return "201503202201451_poprawki events2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
