// <auto-generated />
namespace EventDay.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class poprawaUserProfiles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(poprawaUserProfiles));
        
        string IMigrationMetadata.Id
        {
            get { return "201503102008537_poprawaUserProfiles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
